name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Run the linter
        run: pnpm lint
  test-e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - run: pnpm build:core
      - run: pnpm build:shims
      - run: pnpm playwright install --with-deps
      - run: pnpm -r test:e2e
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - run: pnpm build:core
      - run: pnpm build:shims
      - run: pnpm -r test
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - run: pnpm build:core
      - run: pnpm build:shims
      - run: pnpm typecheck
